openai:
  api_key: xxxxxx
  base_url: xxxxxxxxx
  max_input_tokens: 40000
  model: deepseek-ai/DeepSeek-V3.2
  timeout_seconds: 60
  max_retries: 3
  retry_backoff_seconds: 2
  max_concurrency: 5
project:
  config_file_ext:
  - .yaml
  - .xml
  - .json
  - .conf
  - .ini
  - .toml
  - .config
  - .settings
  exclude_dir:
  - node_modules
  - dist
  - build
  - out
  - venv
  - .venv
  - env
  - target
  - vendor
  - bower_components
  - .git
  - .svn
  - .hg
  - .idea
  - .vscode
  - .metadata
  - nbproject
  - test
  - tests
  - spec
  - specs
  - tmp
  - temp
  - cache
  - logs
  - docker
  - containers
  - k8s
  - kube
  - .circleci
  - .github
  - .travis
  - docs
  - doc
  - .secrets
  - .env
  exclude_max_file_size: 1
  dependency_parse_engine: ast
  source_file_ext:
  - .py
  - .go
  - .js
  - .java
  - .cpp
  - .php
  - .aspx
  - .asp
  - .c
  - .cs
  - .h
  audit_context_depth: 3
  max_audit_nodes: 20
